version: '3'

services:
  reverse-proxy:
    image: traefik:v3.0.0-rc3
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  # web:
  #   image: nginx:stable-alpine3.17
  #   ports:
  #     - 80:80