version: '3'

services:
  reverse-proxy:
    image: traefik:v3.0.0-rc3
    command: --api.dashboard=true --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    labels:
      - "traefik.http.routers.mydashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.mydashboard.service=api@internal"

  
  web:
    image: nginx:stable-alpine3.17
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.nginx.rule=Host(`localhost`)"