version: '3.4'
volumes:
  nexus-data: {}
  postgres_data:

services:
  reverse-proxy:  
    image: traefik:v3.0.0-rc3
    ports:
      - 80:80
      - 443:443
    command:
      - "--configFile=./traefik/traefik.yml"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/traefik
      - './acme.json:/acme.json'

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.cnarasouli.ir`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.options=default"
      - "traefik.http.routers.traefik-secure.tls.certresolver=mycert"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=test-auth"
      - "traefik.http.middlewares.test-auth.basicauth.users=sina:$$apr1$$M5zr5f7l$$biE.q6KJc3mM/Ge9Mn/SU."
        
  web:
    image: nginx:stable-alpine3.17
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.nginx.rule=Host(`cnarasouli.ir`)"
      - "traefik.http.routers.repo-secure.tls=true"
      - "traefik.http.routers.repo-secure.tls.options=default"
      - "traefik.http.routers.repo-secure.tls.certresolver=mycert"
  

  nexus:
    image: klo2k/nexus3
    volumes:
      - "nexus-data:/nexus-data"
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.nexus.rule=Host(`registry.cnarasouli.ir`)"
     - "traefik.http.routers.nexus.tls=true"
     - "traefik.http.routers.nexus.tls.options=default"
     - "traefik.http.routers.nexus.tls.certresolver=mycert"
     - "traefik.http.routers.nexus.service=nexus"
     - "traefik.http.services.nexus.loadbalancer.server.port=8081"

     - "traefik.http.routers.registry.rule=Host(`docker.cnarasouli.ir`)"
     - "traefik.http.routers.registry.tls=true"
     - "traefik.http.routers.registry.tls.certresolver=myresolver"
     - "traefik.http.routers.registry.service=registry-service"
     - "traefik.http.services.registry-service.loadBalancer.server.port=5000"

  db: 
    image: docker.cnarasouli.ir/db/postgres:16.2-bullseye
    environment:
      POSTGRES_USER: "eduhub"
      POSTGRES_PASSWORD: "p2hvVhwn7c4h+jyOOeXZeA=="
      POSTGRES_DB: "eduhub_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  eduhub:
    image: docker.cnarasouli.ir/backend/eduhub:latest
    command: python manage.py runserver 0.0.0.0:8000 
  env_file:
    - .env    
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eduhub.rule=Host(`api.cnarasouli.ir`)"
      - "traefik.http.routers.eduhub.middlewares=add-service-prefix"
      - "traefik.http.middlewares.add-service-prefix.addprefix.prefix=/eduhub"
      - "traefik.http.routers.repo-secure.tls=true"
      - "traefik.http.routers.repo-secure.tls.options=default"
      - "traefik.http.routers.repo-secure.tls.certresolver=mycert"
 
