# Generated by Django 5.0.3 on 2024-05-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_cousersections_course_section_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CouserSections',
            new_name='CouserSelection',
        ),
    ]
