# Generated by Django 5.0.3 on 2024-05-02 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_cousersections_couserselection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.professor'),
            preserve_default=False,
        ),
    ]
